spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/userid
    username: root
    password: Savis@709393
  profiles:
    active :
      prod



  server:
    port: 9090
  spring:
    application:
      name: javainuse
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
---

spring:

  message: "welcome to the dev environment"
server:
  port: 8082